"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&l__4**9bebe+wb($!*t&!e7lc=qjd^!2+oqf=+a7k43osk5ow'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
       "rest_framework",
    "corsheaders",
    "enquiries",
 
]


# JAZZMIN_SETTINGS = {
#     # Branding
#     "site_title": "SPS Engineering Admin",
#     "site_header": "SPS Engineering Solutions",
#     "site_brand": "SPS Engineering",
#     "site_logo": None,
#     "login_logo": None,
#     "login_logo_dark": None,
    
    
#     "site_logo": "images/sps-final-logo.png",
#     "login_logo": "images/sps-final-logo.png",
#     "login_logo_dark": "images/sps-final-logo.png",

#     # Welcome text
#     "welcome_sign": "Welcome to SPS Engineering Solutions",
#     "copyright": "SPS Engineering Solutions",

#     # Search
#     "search_model": [
#         "enquiries.Enquiry",
#     ],

#     # UI
#     "show_sidebar": True,
#     "navigation_expanded": True,

#     "hide_apps": [],
#     "hide_models": [],

#     # Top menu
#     "topmenu_links": [
#         {
#             "name": "Home",
#             "url": "admin:index",
#             "permissions": ["auth.view_user"],
#         },
#         {
#             "app": "enquiries",
#         },
#     ],

#     # User menu
#     "usermenu_links": [
#         {
#             "name": "SPS Website",
#             "url": "http://localhost:3000",
#             "new_window": True,
#         },
#     ],

#     # Icons
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",

#         "enquiries": "fas fa-envelope",
#         "enquiries.Enquiry": "fas fa-file-signature",
#     },

#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-circle",

#     # Modal
#     "related_modal_active": False,

#     # UI builder
#     "show_ui_builder": False,

#     # Change form
#     "changeform_format": "horizontal_tabs",
# }


JAZZMIN_SETTINGS = {
    "site_title": "SPS Engineering Admin",
    "site_header": "SPS Engineering Solutions",
    "site_brand": "SPS Engineering",

    "site_logo": "images/sps-final-logo.png",
    "login_logo": "images/sps-final-logo.png",
    # "login_logo_dark": "images/sps-final-logo.png",

    "welcome_sign": "Welcome to SPS Engineering Solutions",
    "copyright": "SPS Engineering Solutions",

    "custom_css": "css/admin.css",

    "search_model": [
        "enquiries.Enquiry",
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "hide_apps": [],
    "hide_models": [],

    "topmenu_links": [
        {
            "name": "Home",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
        {
            "app": "enquiries",
        },
    ],

    "usermenu_links": [
        {
            "name": "SPS Website",
            "url": "http://localhost:3000",
            "new_window": True,
        },
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "enquiries": "fas fa-envelope",
        "enquiries.Enquiry": "fas fa-file-signature",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": False,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    "brand_colour": "navbar-dark",
    "accent": "accent-lime",

    "navbar": "navbar-dark",
    "no_navbar_border": True,

    "navbar_fixed": True,
    "layout_boxed": False,

    "footer_fixed": False,
    "sidebar_fixed": True,

    "sidebar": "sidebar-dark-lime",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    "theme": "darkly",
    "dark_mode_theme": "darkly",

    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
