# Generated by Django 4.2 on 2026-07-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('steel_fabrication', 'Steel Fabrication'), ('structural_erection', 'Structural Erection'), ('peb_solutions', 'PEB Solutions'), ('roofing_cladding', 'Roofing & Cladding'), ('industrial_piping', 'Industrial Piping'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Enquiry',
                'verbose_name_plural': 'Project Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
