# Generated by Django 4.2 on 2026-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='facility',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
